name: Outputs Workflow 1

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.url1 }}
  
    steps:
      - id: step1
        run: |
          "url1=https://abc.com" >> "$GITHUB_OUTPUT"
          echo "${{ steps.step1.outputs.url }}"


