name: Outputs Workflow 1

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.var1 }}
    steps:
      - id: step1
        run: |
          echo "var1=Hello World" >> "$GITHUB_OUTPUT"
          echo "output1 is ${{ steps.step1.outputs.var1 }}"
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Accessing output1 from a dependent job - ${{ needs.job1.outputs.var1 }}"


