name: Ruby workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ruby-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  #checks out the repository to the workspace

      - uses: ruby/setup-ruby@v1  #sets up ruby 
        with:
          ruby-version: '3.3'  

      - run: ruby ./ruby-files/print-string.rb  #runs ruby file
